### PR TITLE
Feature: add option to filter hover-info text

### PR DESCRIPTION
**Pull request by yangqian**
Add option config.defaults.filter to filter out unnecessary atrributes from hover-info.
```yaml
config:
  defaults:
    hover_action: hover-info
    hove_info_filter:
      - sensor_type
      - ...
```
Hover-info before:
before
after:
after

### CODE REVIEW

**Comment by exetico** [comment]
Hi

Thank you for the PR. I've not yet reviewed the code.

But while waiting, please add the details to the docs too. 😊

**Comment by exetico** [comment]
Thank you for the docs-update, too. There's a few things, where I've added a comment.

**Comment by yangqian** [comment]
> Thank you for the docs-update, too. There's a few things, where I've added a comment.

Sorry, where could I find the comments?

**Comment by yangqian** [comment]
> 

Thanks. I've submited another commit. Coud you check it out again?

**Comment by exetico** [comment]
Hi,

Looks fine. Maybe a single type, but I'll fix that.

Before:
image

After:
image

Used with:
```yaml
defaults:
     hover_action: hover-info
     hover_info_filter: 
      - color_mode
      - supported_features
      - supported_color_modes
      - min_mireds
      - max_mireds
      - icon
```

**Comment by exetico** [comment]
Thank you. It's now released in:
https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.31

**Pull request merged**
