### PR TITLE
fix bug with multiple service calls

### PR DESCRIPTION
**Pull request by regevbr**
consider the following config:
```yaml
type: custom:floorplan-card
config:
  image: /local/floorplan/home/home.svg
  rules:
    - entity: light.bedroom_light_bulb
      entities:
        - switch.bedroom_light_switch
      element: light.bedroom
      double_tap_action: more-info
      hover_action: hover-info
      tap_action:
        action: call-service
        service: >
          > if (entity.entity_id ===
          'switch.bedroom_light_switch') {
            return 'switch.toggle';
          } else {
            return 'none.none';
          }
        service_data:
          entity_id: switch.bedroom_light_switch_local
```
When clicking the element, it causes the service to be called 4 times, instead of just 2, rendering unwanted results!
This happens due to the fact that the ManyClicks handler is registred twice, and also the singleClick event is registred twice, which causes each click to run 2*2 times.
The solution is to avoid multiple registrations on the same element in ManyClicks.

I tested the solution locally and it works!

i.e.
If you wonder why I need this strange config, it is because I want the more-info handlers to operate on one entity, but to watch the states of another (which refelcts state changes faster)

### CODE REVIEW

**Comment by regevbr** [comment]
@exetico can you please CR?

**Comment by exetico** [comment]
Hi @regevbr 

Thank you for the PR. Have you tested the normal functions (singleClick and manyClick including hover), after the refactoring of the code? I'm not able to make a full test now, so I would like to hear your inputs on that part. The changes itself looks just fine.

**Comment by regevbr** [comment]
> Hi @regevbr
> 
> Thank you for the PR. Have you tested the normal functions (singleClick and manyClick including hover), after the refactoring of the code? I'm not able to make a full test now, so I would like to hear your inputs on that part. The changes itself looks just fine.

Hi,

Indeed everything works as expected!

**Comment by exetico** [comment]
Thanks. I'll merge the changes, but also confirm it at my end.

**Comment by exetico** [comment]
Oh wow, what a day 😂. I handled that a bit too fast.

**Pull request merged**
