### PR TITLE
Fix issue with "url" action

### PR DESCRIPTION
**Pull request by arnaupv**
Both [navigate](https://github.com/arnaupv/ha-floorplan/blob/master/src/components/floorplan/floorplan-element.ts#L1714) and [url](https://github.com/arnaupv/ha-floorplan/blob/master/src/components/floorplan/floorplan-element.ts#L1724) lead to the same function and [action](https://github.com/arnaupv/ha-floorplan/blob/e0c6e9fb964127baf7f38969ea153b9b8d37443c/src/lib/homeassistant/common/navigate.ts#L14-L31) 

Getting the same behaviour when we do:
```
  tap_action:
    action: url
    url_path: https://localhost:8123/lovelace/floor02
```
or 
```
  tap_action:
    action: navigate
    navigation_path: /lovelace/floor02
```

With the update present in this PR, we want to be able to be redirected to an external link. For instance:
```
  tap_action:
    action: url
    url_path: https://www.google.com
```

### CODE REVIEW

**Comment by exetico** [comment]
Hi

Thank you for your PR. As discussed [here](https://github.com/ExperienceLovelace/ha-floorplan/discussions/181), it's important for me to follow the HA-way of doing things:
https://github.com/home-assistant/frontend/blob/08863348dc64d826dc038b6193e7c31b42d04057/src/panels/lovelace/common/handle-action.ts#L116

Therefore we'll need to use `window.open` instead, and consider to add extra features on top, if needed. It would be a modifier to open as a new tab - see my comment [here](https://github.com/ExperienceLovelace/ha-floorplan/discussions/181#discussioncomment-1932165).

**Comment by arnaupv** [comment]
Hi @exetico  thanks for redirection to such discussion. I've added the `window.open` with the `_bank` parameter in order to ensure a new tab is created (recommended based on the discussion)  instead of opening it in the same tab. Is this ok, then?

**Comment by OzGav** [comment]
Can’t believe you happened to open this PR when I was just talking about it in the discussion! Thanks for contributing!

**Comment by arnaupv** [comment]
> Can’t believe you happened to open this PR when I was just talking about it in the discussion! Thanks for contributing!

Hi, yeah, to be honest I did not see your discussion :) (sorry for that...). 

However, what I'm proposing is not good enough.
In case I click twice on the same element, 2 tabs will be opened. Ideally,  only 1 tab would be opened, and the second click would redirect to the tab which had been opened in the first click. What do you think?

**Comment by OzGav** [comment]
Yeah if you could achieve that it would be perfect but I am happy for it just to work at the moment!

**Comment by exetico** [comment]
Hi @arnaupv 

It's great to see things moving fast, now that I've not found time to fix this.

Could I ask you to consider an option to trigger `_self` with a secondary variable? It could be `url_self` or like that.
Another solution would be to just add `url_windowname` as an secondary variable, and let the user define the windowName - and default to `_blank`, it nothings provided? 

I'm sorry for being a bit piggy here. But it would be great to have both cases fixed, at the same time.

**Comment by arnaupv** [comment]
Hi @exetico , I've adde thet parameter "same_tab". If nothing is defined, by default another tab  is opened (`_blank`).

**Comment by exetico** [comment]
Hi @arnaupv . Thanks for the corrections! It's always funny that the testing itself, often takes longer that the code itself. But I'm happy to see people bringing things on the table - no matter the scope.

I've tested it on my local instance, and can't find any problems. 

If you find time, kindly push to the docs too (as you mentioned), and please try and keep the same kind of "formattings", as we've used today :-)

I'm sure that @OzGav are happy with the changes. Next time, I'll take my s**t together, and find the required 5 minutes myself 😆 .

**Comment by exetico** [comment]
Pushed to https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.30

I'll be happy to take the updated docs, whenever it's ready 😄 .

**Pull request merged**
